# Generated by Django 5.2 on 2026-05-23 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_requirement_linked_requirements_requirement_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='department',
            field=models.CharField(blank=True, choices=[('DSE', 'DSE'), ('DEE', 'DEE'), ('SS', 'SS'), ('MS', 'MS'), ('DGE', 'DGE'), ('DPS', 'DPS'), ('Other', 'Other'), ('Tech Initiatives', 'Tech Initiatives')], max_length=20),
        ),
        migrations.CreateModel(
            name='RequirementGrooming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wireframe_file', models.FileField(blank=True, null=True, upload_to='grooming/wireframes/')),
                ('wireframe_filename', models.CharField(blank=True, max_length=255)),
                ('wireframe_signed_at', models.DateTimeField(blank=True, null=True)),
                ('stakeholder_file', models.FileField(blank=True, null=True, upload_to='grooming/stakeholder/')),
                ('stakeholder_filename', models.CharField(blank=True, max_length=255)),
                ('stakeholder_signed_at', models.DateTimeField(blank=True, null=True)),
                ('tl_comment', models.TextField(blank=True)),
                ('tl_commented_at', models.DateTimeField(blank=True, null=True)),
                ('pm_comment', models.TextField(blank=True)),
                ('pm_commented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pm_commented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_grooming_comments', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grooming', to='projects.requirement')),
                ('stakeholder_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholder_signoffs', to=settings.AUTH_USER_MODEL)),
                ('tl_commented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_grooming_comments', to=settings.AUTH_USER_MODEL)),
                ('wireframe_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wireframe_signoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requirement_grooming',
            },
        ),
    ]
