# Generated by Django 5.2 on 2026-05-23 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_requirement_department_requirementgrooming'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('yesterday', models.TextField(blank=True)),
                ('today', models.TextField()),
                ('blockers', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standups', to='projects.sprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'standups',
                'ordering': ['-date', '-submitted_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
