# Generated by Django 5.2 on 2026-05-23 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMWorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('documentation', 'Documentation'), ('learning', 'Learning'), ('internal_discussion', 'Internal Discussion'), ('external_discussion', 'External Discussion'), ('online_discussion', 'Online Discussion'), ('grooming_discussion', 'Grooming Discussion'), ('tech_discussion', 'Tech Discussion'), ('pmu_discussion', 'PMU Discussion')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_work_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pm_work_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMWorkEntryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pm_work_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.pmworkentry')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_work_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pm_work_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMWorkEntryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_work_comments', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.pmworkentry')),
            ],
            options={
                'db_table': 'pm_work_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
