# Generated by Django 5.2 on 2026-05-23 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_pm_work_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('meeting_type', models.CharField(choices=[('standup', 'Daily Standup'), ('sprint_planning', 'Sprint Planning'), ('sprint_review', 'Sprint Review'), ('retrospective', 'Retrospective'), ('grooming', 'Grooming Session'), ('stakeholder', 'Stakeholder Meeting'), ('one_on_one', '1-on-1'), ('technical', 'Technical Discussion'), ('general', 'General Meeting')], default='general', max_length=20)),
                ('color', models.CharField(default='#1a56db', max_length=10)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ScrumAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('standup', 'Standup Time'), ('breach', 'Sprint Breach'), ('urgent', 'Urgent'), ('info', 'General Info')], default='standup', max_length=20)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrum_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scrum_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
